/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/request-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Link */
        post: operations["request_link_auth_request_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_auth_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_auth_me_patch"];
        trace?: never;
    };
    "/auth/me/changelog-seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Changelog Seen */
        post: operations["changelog_seen_auth_me_changelog_seen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/next-today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Matches Today */
        get: operations["next_matches_today_matches_next_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/in-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** In Progress Matches */
        get: operations["in_progress_matches_matches_in_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matches Today */
        get: operations["matches_today_matches_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List News */
        get: operations["list_news_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Pools */
        get: operations["my_pools_pools_get"];
        put?: never;
        /** Create Pool */
        post: operations["create_pool_pools_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Pool */
        post: operations["join_pool_pools_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pool Detail */
        get: operations["pool_detail_pools__pool_id__get"];
        put?: never;
        post?: never;
        /** Delete Pool */
        delete: operations["delete_pool_pools__pool_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Leave Pool */
        delete: operations["leave_pool_pools__pool_id__leave_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pool Leaderboard */
        get: operations["pool_leaderboard_pools__pool_id__leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}/leaderboard/weekly-hero": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pool Weekly Hero */
        get: operations["pool_weekly_hero_pools__pool_id__leaderboard_weekly_hero_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}/leaderboard/weekly-titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pool Weekly Titles */
        get: operations["pool_weekly_titles_pools__pool_id__leaderboard_weekly_titles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Predictions */
        get: operations["my_predictions_pools__pool_id__predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}/predictions/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Prediction */
        put: operations["upsert_prediction_pools__pool_id__predictions__match_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}/predictions/revealed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revealed Predictions */
        get: operations["revealed_predictions_pools__pool_id__predictions_revealed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/{match_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Result */
        post: operations["set_result_admin_matches__match_id__result_post"];
        /** Clear Result */
        delete: operations["clear_result_admin_matches__match_id__result_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore User */
        post: operations["restore_user_admin_users__user_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminStatsOut */
        AdminStatsOut: {
            /** Total Users */
            total_users: number;
            /** Onboarded Users */
            onboarded_users: number;
            /** Active Users */
            active_users: number;
            /** Total Pools */
            total_pools: number;
            /** Avg Pool Size */
            avg_pool_size: number;
            /** Total Predictions */
            total_predictions: number;
            /** Predictions By Stage */
            predictions_by_stage: {
                [key: string]: number;
            };
            match_counts: components["schemas"]["MatchStatusCountsOut"];
        };
        /** ChangelogSeenIn */
        ChangelogSeenIn: {
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderboardOut */
        LeaderboardOut: {
            /** Pool Id */
            pool_id: string;
            /** Rows */
            rows: components["schemas"]["LeaderboardRowOut"][];
        };
        /** LeaderboardRowOut */
        LeaderboardRowOut: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Points */
            points: number;
            /** Exact Count */
            exact_count: number;
            /** Near Count */
            near_count: number;
            /** Margin Count */
            margin_count: number;
            /** Outcome Count */
            outcome_count: number;
            /** Predictions Made */
            predictions_made: number;
        };
        /** MatchOut */
        MatchOut: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            stage: components["schemas"]["Stage"];
            /** Round Weight */
            round_weight: number;
            /** Group Label */
            group_label: string | null;
            /** Slot Label */
            slot_label: string | null;
            /** Home Team Id */
            home_team_id: string | null;
            /** Away Team Id */
            away_team_id: string | null;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            status: components["schemas"]["MatchStatus"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /** Advancing Team Id */
            advancing_team_id: string | null;
            /** Is Locked */
            is_locked: boolean;
        };
        /** MatchRevealedOut */
        MatchRevealedOut: {
            /** Match Id */
            match_id: string;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            status: components["schemas"]["MatchStatus"];
            /** Home Team Name */
            home_team_name: string | null;
            /** Away Team Name */
            away_team_name: string | null;
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /** Entries */
            entries: components["schemas"]["PredictionEntryOut"][];
        };
        /**
         * MatchStatus
         * @enum {string}
         */
        MatchStatus: "scheduled" | "locked" | "final";
        /** MatchStatusCountsOut */
        MatchStatusCountsOut: {
            /** Scheduled */
            scheduled: number;
            /** Locked */
            locked: number;
            /** Final */
            final: number;
        };
        /** MatchTodayOut */
        MatchTodayOut: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            status: components["schemas"]["MatchStatus"];
            /** Home Name */
            home_name: string | null;
            /** Home Flag */
            home_flag: string | null;
            /** Away Name */
            away_name: string | null;
            /** Away Flag */
            away_flag: string | null;
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /** Group Label */
            group_label: string | null;
            stage: components["schemas"]["Stage"];
        };
        /** MemberOut */
        MemberOut: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["MemberRole"];
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /**
         * MemberRole
         * @enum {string}
         */
        MemberRole: "creator" | "member";
        /** MessageOut */
        MessageOut: {
            /** Message */
            message: string;
        };
        /** NewsItemOut */
        NewsItemOut: {
            source: components["schemas"]["NewsSource"];
            /** Title */
            title: string;
            /** Link */
            link: string;
            /** Summary */
            summary: string;
            /** Image Url */
            image_url: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /**
         * NewsSource
         * @enum {string}
         */
        NewsSource: "espn" | "ge" | "trivela";
        /** NextMatchTodayOut */
        NextMatchTodayOut: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            /** Home Name */
            home_name: string | null;
            /** Home Flag */
            home_flag: string | null;
            /** Away Name */
            away_name: string | null;
            /** Away Flag */
            away_flag: string | null;
            /** Group Label */
            group_label: string | null;
            stage: components["schemas"]["Stage"];
        };
        /** PoolCreateIn */
        PoolCreateIn: {
            /** Name */
            name: string;
        };
        /** PoolJoinIn */
        PoolJoinIn: {
            /** Invite Code */
            invite_code: string;
        };
        /** PoolOut */
        PoolOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Invite Code */
            invite_code: string;
            /** Invite Url */
            invite_url: string;
            /** Creator Id */
            creator_id: string;
            /** Members */
            members: components["schemas"]["MemberOut"][];
            /** Is Creator */
            is_creator: boolean;
            /** Has Pending Today */
            has_pending_today: boolean;
        };
        /** PoolSummaryOut */
        PoolSummaryOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Invite Code */
            invite_code: string;
            /** Member Count */
            member_count: number;
            /** Is Creator */
            is_creator: boolean;
            /** Has Pending Today */
            has_pending_today: boolean;
        };
        /** PredictionEntryOut */
        PredictionEntryOut: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
            /** Advancing Team Id */
            advancing_team_id: string | null;
            /** Points */
            points: number | null;
        };
        /** PredictionIn */
        PredictionIn: {
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
            /** Advancing Team Id */
            advancing_team_id?: string | null;
        };
        /** PredictionOut */
        PredictionOut: {
            /** Match Id */
            match_id: string;
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
            /** Advancing Team Id */
            advancing_team_id: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RequestLinkIn */
        RequestLinkIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ResultIn */
        ResultIn: {
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
            /** Advancing Team Id */
            advancing_team_id?: string | null;
        };
        /** RevealedPredictionsOut */
        RevealedPredictionsOut: {
            /** Pool Id */
            pool_id: string;
            /** Matches */
            matches: components["schemas"]["MatchRevealedOut"][];
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "group" | "r32" | "r16" | "qf" | "sf" | "third" | "final";
        /** TeamOut */
        TeamOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Group Label */
            group_label: string | null;
            /** Flag Emoji */
            flag_emoji: string;
        };
        /** UpdateProfileIn */
        UpdateProfileIn: {
            /** Display Name */
            display_name: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Is Admin */
            is_admin: boolean;
            /** Onboarding Done */
            onboarding_done: boolean;
            /** Last Viewed Changelog Version */
            last_viewed_changelog_version: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyIn */
        VerifyIn: {
            /** Token */
            token: string;
        };
        /** WeeklyHeroOut */
        WeeklyHeroOut: {
            /** Pool Id */
            pool_id: string;
            /** Week Label */
            week_label: string;
            /** Profeta Name */
            profeta_name: string | null;
            /** Profeta Points */
            profeta_points: number | null;
            /** Corneteiro Name */
            corneteiro_name: string | null;
            /** Corneteiro Points */
            corneteiro_points: number | null;
            /** Has Data */
            has_data: boolean;
            /** Narrative */
            narrative?: string | null;
        };
        /** WeeklyTitleCountOut */
        WeeklyTitleCountOut: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Profeta Count */
            profeta_count: number;
            /** Profissional Count */
            profissional_count: number;
            /** Botequeiro Count */
            botequeiro_count: number;
            /** Corneteiro Count */
            corneteiro_count: number;
        };
        /** WeeklyTitlesOut */
        WeeklyTitlesOut: {
            /** Pool Id */
            pool_id: string;
            /** Weeks Counted */
            weeks_counted: number;
            /** Rows */
            rows: components["schemas"]["WeeklyTitleCountOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    request_link_auth_request_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestLinkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_auth_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    changelog_seen_auth_me_changelog_seen_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangelogSeenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"][];
                };
            };
        };
    };
    next_matches_today_matches_next_today_get: {
        parameters: {
            query?: {
                window_end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextMatchTodayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    in_progress_matches_matches_in_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextMatchTodayOut"][];
                };
            };
        };
    };
    matches_today_matches_today_get: {
        parameters: {
            query: {
                day_start: string;
                day_end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchTodayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_matches_get: {
        parameters: {
            query?: {
                stage?: components["schemas"]["Stage"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_news_news_get: {
        parameters: {
            query?: {
                day_start?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_pools_pools_get: {
        parameters: {
            query?: {
                window_end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pool_pools_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PoolCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_pool_pools_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PoolJoinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pool_detail_pools__pool_id__get: {
        parameters: {
            query?: {
                window_end?: string | null;
            };
            header?: never;
            path: {
                pool_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pool_pools__pool_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pool_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_pool_pools__pool_id__leave_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pool_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pool_leaderboard_pools__pool_id__leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pool_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pool_weekly_hero_pools__pool_id__leaderboard_weekly_hero_get: {
        parameters: {
            query: {
                week_start: string;
                week_end: string;
            };
            header?: never;
            path: {
                pool_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyHeroOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pool_weekly_titles_pools__pool_id__leaderboard_weekly_titles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pool_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyTitlesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_predictions_pools__pool_id__predictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pool_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_prediction_pools__pool_id__predictions__match_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pool_id: string;
                match_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revealed_predictions_pools__pool_id__predictions_revealed_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pool_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealedPredictionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_result_admin_matches__match_id__result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_result_admin_matches__match_id__result_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_user_admin_users__user_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
