/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/request-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Link */
        post: operations["request_link_auth_request_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Pools */
        get: operations["my_pools_pools_get"];
        put?: never;
        /** Create Pool */
        post: operations["create_pool_pools_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Pool */
        post: operations["join_pool_pools_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pool Detail */
        get: operations["pool_detail_pools__pool_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pool Leaderboard */
        get: operations["pool_leaderboard_pools__pool_id__leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Predictions */
        get: operations["my_predictions_pools__pool_id__predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{pool_id}/predictions/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Prediction */
        put: operations["upsert_prediction_pools__pool_id__predictions__match_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/{match_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Result */
        post: operations["set_result_admin_matches__match_id__result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderboardOut */
        LeaderboardOut: {
            /** Pool Id */
            pool_id: string;
            /** Rows */
            rows: components["schemas"]["LeaderboardRowOut"][];
        };
        /** LeaderboardRowOut */
        LeaderboardRowOut: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Points */
            points: number;
            /** Exact Count */
            exact_count: number;
            /** Predictions Made */
            predictions_made: number;
        };
        /** MatchOut */
        MatchOut: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            stage: components["schemas"]["Stage"];
            /** Round Weight */
            round_weight: number;
            /** Group Label */
            group_label: string | null;
            /** Slot Label */
            slot_label: string | null;
            /** Home Team Id */
            home_team_id: string | null;
            /** Away Team Id */
            away_team_id: string | null;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            status: components["schemas"]["MatchStatus"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /** Advancing Team Id */
            advancing_team_id: string | null;
            /** Is Locked */
            is_locked: boolean;
        };
        /**
         * MatchStatus
         * @enum {string}
         */
        MatchStatus: "scheduled" | "locked" | "final";
        /** MemberOut */
        MemberOut: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["MemberRole"];
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /**
         * MemberRole
         * @enum {string}
         */
        MemberRole: "creator" | "member";
        /** MessageOut */
        MessageOut: {
            /** Message */
            message: string;
        };
        /** PoolCreateIn */
        PoolCreateIn: {
            /** Name */
            name: string;
        };
        /** PoolJoinIn */
        PoolJoinIn: {
            /** Invite Code */
            invite_code: string;
        };
        /** PoolOut */
        PoolOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Invite Code */
            invite_code: string;
            /** Invite Url */
            invite_url: string;
            /** Creator Id */
            creator_id: string;
            /** Members */
            members: components["schemas"]["MemberOut"][];
            /** Is Creator */
            is_creator: boolean;
        };
        /** PoolSummaryOut */
        PoolSummaryOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Invite Code */
            invite_code: string;
            /** Member Count */
            member_count: number;
            /** Is Creator */
            is_creator: boolean;
        };
        /** PredictionIn */
        PredictionIn: {
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
            /** Advancing Team Id */
            advancing_team_id?: string | null;
        };
        /** PredictionOut */
        PredictionOut: {
            /** Match Id */
            match_id: string;
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
            /** Advancing Team Id */
            advancing_team_id: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RequestLinkIn */
        RequestLinkIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** ResultIn */
        ResultIn: {
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
            /** Advancing Team Id */
            advancing_team_id?: string | null;
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "group" | "r32" | "r16" | "qf" | "sf" | "third" | "final";
        /** TeamOut */
        TeamOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Group Label */
            group_label: string | null;
            /** Flag Emoji */
            flag_emoji: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Is Admin */
            is_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyIn */
        VerifyIn: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    request_link_auth_request_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestLinkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_auth_verify_post: {
        parameters: {
            query?: {
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"][];
                };
            };
        };
    };
    list_matches_matches_get: {
        parameters: {
            query?: {
                stage?: components["schemas"]["Stage"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_pools_pools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pool_pools_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PoolCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_pool_pools_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PoolJoinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pool_detail_pools__pool_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pool_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pool_leaderboard_pools__pool_id__leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pool_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_predictions_pools__pool_id__predictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pool_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_prediction_pools__pool_id__predictions__match_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pool_id: string;
                match_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_result_admin_matches__match_id__result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: {
                bolao_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
